package com.mingcapstone.quickmealplanner.entity;

public enum MealType {
    MONDAY_LUNCH, MONDAY_DINNER, 
    TUESDAY_LUNCH, TUESDAY_DINNER, 
    WEDNESDAY_LUNCH, WEDNESDAY_DINNER,
    THURSDAY_LUNCH, THURSDAY_DINNER,
    FRIDAY_LUNCH, FRIDAY_DINNER,
    SATURDAY_LUNCH, SATURDAY_DINNER,
    SUNDAY_LUNCH, SUNDAY_DINNER
}
